site_name: Hecatomb
site_url: "https://github.com/shandley/hecatomb"
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - shell
        - text
nav:
    - ABOUT:
      - Motivation: index.md
      - Pipeline: pipeline.md
      - Databases: databases.md
      - Outputs: outputs.md
    - RUNNING:
      - Install: install.md
      - Usage: usage.md
      - Profiles: profiles.md
      - Configuration: configuration.md
      - Advanced: advanced.md
      - FAQ: faq.md
    - TUTORIAL:
      - 'Part 1: Preparation': tutorialPt1.md
      - 'Part 2: Filtering annotations': tutorialPt2.md
      - 'Part 3: Visualising annotations': tutorialPt3.md
      - 'Part 4: Statistical tests': tutorialPt4.md
      - 'Part 5: Contig annotations': tutorialPt5.md
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets