# For more information see: https://github.com/shandley/hecatomb and https://hecatomb.readthedocs.io/en/latest/
resources:
    big:
        mem: 64000
        mem_mb: 64000
        cpu: 32
        time: 1440
    lrg:
        mem: 32000
        mem_mb: 32000
        cpu: 16
        time: 240
    med:
        mem: 16000
        mem_mb: 16000
        cpu: 8
        time: 240
    sml:
        mem: 2000
        mem_mb: 2000
        cpu: 1
        time: 60
    ram:
        mem: 16000
        mem_mb: 16000
        cpu: 2
        time: 240
hecatomb:
    args:
        reads: "test_data"
        output: "hecatomb.out/"
        search: "fast"
        host: "human"
        trim:
            - host_rm
            - fastp
#            - prinseq
#            - roundAB
#            - notrim
#            - cutadapt
#            - filtlong
#            - subsample
        combineRuns: false
        simulate: false
        testing: true
        hostFa:
        assembly: "cross"
        longreads: false
        output_paths:
            results: "results/"
            reports: "reports/"
            temp: "temp/"
            log: "logs/"
            bench: "benchmarks/"
            hecatomb_log: "hecatomb.log"
        temp_paths:
            assembly: "assembly/"
            mapping: "mapping/"
            primaryAA: "mmseqs_aa_primary/"
            secondaryAA: "mmseqs_aa_secondary/"
            primaryNT: "mmseqs_nt_primary/"
            secondaryNT: "mmseqs_nt_secondary/"
        databases:
        database_paths:
            contaminants: "contaminants/"
            taxonomy: "taxonomy/"
            tables: "tables/"
            hostBase: "host/"
            primaryAA: "aa/virus_primary_aa/"
            primaryNT: "nt/virus_primary_nt/"
            secondaryAA: "aa/virus_secondary_aa/"
            secondaryNT: "nt/virus_secondary_nt/"
        custom_aa:
        custom_nt:
    container:
        bbmap_bedtools_pigz_flye:
            "oras://quay.io/beardymcjohnface/hecatomb_bbmap_bedtools_pigz_flye:0.0.1"
#            "hecatomb-containers/containers/bbmap_bedtools_pigz_flye.sif"
        canu:
            "oras://quay.io/beardymcjohnface/hecatomb_canu:0.0.1"
#            "hecatomb-containers/containers/canu.sif"
        krona_curl_zstd_pysam:
            "oras://quay.io/beardymcjohnface/hecatomb_krona_curl_zstd_pysam:0.0.1"
#            "hecatomb-containers/containers/krona_curl_zstd_pysam.sif"
        megahit:
            "oras://quay.io/beardymcjohnface/hecatomb_megahit:0.0.1"
#            "hecatomb-containers/containers/megahit.sif"
        minimap2_samtools:
            "oras://quay.io/beardymcjohnface/hecatomb_minimap2_samtools:0.0.1"
#            "hecatomb-containers/containers/minimap2_samtools.sif"
        mmseqs2_seqkit_taxonkit_csvtk:
            "oras://quay.io/beardymcjohnface/hecatomb_mmseqs2_seqkit_taxonkit_csvtk:0.0.1"
#            "hecatomb-containers/containers/mmseqs2_seqkit_taxonkit_csvtk.sif"
    addHost:
        minViralAlnLen:
            1000
    mmseqs:
        linclustParams:
            --kmer-per-seq-scale 0.3
            -c 0.8
            --cov-mode 1
            --min-seq-id 0.97
            --alignment-mode 3
        filtAA:
            --min-length 30
            -e 1e-5
        filtNT:
            --min-length 90
            -e 1e-20
        sensitive:
            --start-sens 2
            --sens-steps 3
            -s 7
        fast:
            -s 4
        taxIdIgnore: 0 1 2 10239 131567 12429 2759      # TaxIDs to defer to topHit rather than LCA
    assembly:
        canu:
            correctedErrorRate=0.16
            maxInputCoverage=10000
            minInputCoverage=0
            corOutCoverage=10000
            corMhapSensitivity=high
            corMinCoverage=0
            useGrid=False
            stopOnLowCoverage=False
            genomeSize=10M
            -nanopore
        megahit:
            --presets meta-large
        flye:
            -g 1g
        metaflye:
            --meta
            -g 1g
            --nano-raw
trimnami:
    qc:
        compression:
            1
        minimapIndex:
            -I 8G
        hostRemoveFlagstat:
            -f 4
            -F 3584
        cutadapt:
            -m 40
        fastp:
            --qualified_quality_phred 15
            --length_required 90
            --cut_tail 
            --cut_tail_window_size 25
            --cut_tail_mean_quality 15
            --dedup
            --dup_calc_accuracy 4
            --trim_poly_x
            --detect_adapter_for_pe
        prinseq:
            -min_len 60 
            -min_qual_mean 25 
            -ns_max_n 1 
            -derep 1
            -out_format 0 
            -trim_tail_left 5 
            -trim_tail_right 5
            -ns_max_n 5  
            -trim_qual_type min 
            -trim_qual_left 30
            -trim_qual_right 30 
            -trim_qual_window 10
        filtlong:
            --min_length 1000
            --keep_percent 95
