# For more information see: https://github.com/shandley/hecatomb and https://hecatomb.readthedocs.io/en/latest/
resources:
    big:
        mem: 64000
        cpu: 32
        time: "24:00:00"
    lrg:
        mem: 32000
        cpu: 16
        time: "04:00:00"
    med:
        mem: 16000
        cpu: 8
        time: "04:00:00"
    sml:
        mem: 2000
        cpu: 1
        time: "01:00:00"
    ram:
        mem: 16000
        cpu: 2
        time: "04:00:00"
hecatomb:
    addHost:
        minViralAlnLen:
            1000
    mmseqs:
        linclustParams:
            --kmer-per-seq-scale 0.3
            -c 0.8
            --cov-mode 1
            --min-seq-id 0.97
            --alignment-mode 3
        filtAA:
            --min-length 30
            -e 1e-5
        filtNT:
            --min-length 90
            -e 1e-20
        sensitive:
            --start-sens 2
            --sens-steps 3
            -s 7
        fast:
            -s 4
        taxIdIgnore: 0 1 2 10239 131567 12429 2759      # TaxIDs to defer to topHit rather than LCA
    assembly:
        canu:
            correctedErrorRate=0.16
            maxInputCoverage=10000
            minInputCoverage=0
            corOutCoverage=10000
            corMhapSensitivity=high
            corMinCoverage=0
            useGrid=False
            stopOnLowCoverage=False
            genomeSize=10M
            -nanopore
        megahit:
            --presets meta-large
        flye:
            -g 1g
        metaflye:
            --meta
            -g 1g
            --nano-raw
trimnami:
    qc:
        compression:
            1
        minimapIndex:
            -I 8G
        hostRemoveFlagstat:
            -f 4
            -F 3584
        cutadapt:
            -m 40
        fastp:
            --qualified_quality_phred 15
            --length_required 90
            --cut_tail 
            --cut_tail_window_size 25
            --cut_tail_mean_quality 15
            --dedup
            --dup_calc_accuracy 4
            --trim_poly_x
            --detect_adapter_for_pe
        prinseq:
            -min_len 60 
            -min_qual_mean 25 
            -ns_max_n 1 
            -derep 1
            -out_format 0 
            -trim_tail_left 5 
            -trim_tail_right 5
            -ns_max_n 5  
            -trim_qual_type min 
            -trim_qual_left 30
            -trim_qual_right 30 
            -trim_qual_window 10
        filtlong:
            --min_length 1000
            --keep_percent 95
