hecatomb:
    dbs:
        mirror1: "https://hecatombdatabases.s3.us-west-2.amazonaws.com/databases/"
        mirror2: "https://htcf.wustl.edu/files/lXraB7eg/hecatomb/"
        files:
            - contaminants/nebnext_adapters.fa
            - contaminants/primerB.fa
            - contaminants/rc_primerB_ad6.fa
            - contaminants/truseq.fa
            - contaminants/vector_contaminants.fa
            - aa/virus_primary_aa/sequenceDB
            - aa/virus_primary_aa/sequenceDB.dbtype
            - aa/virus_primary_aa/sequenceDB_delnodes.dmp
            - aa/virus_primary_aa/sequenceDB_h
            - aa/virus_primary_aa/sequenceDB_h.dbtype
            - aa/virus_primary_aa/sequenceDB_h.index
            - aa/virus_primary_aa/sequenceDB.index
            - aa/virus_primary_aa/sequenceDB.lookup
            - aa/virus_primary_aa/sequenceDB_mapping
            - aa/virus_primary_aa/sequenceDB_merged.dmp
            - aa/virus_primary_aa/sequenceDB_names.dmp
            - aa/virus_primary_aa/sequenceDB_nodes.dmp
            - aa/virus_primary_aa/sequenceDB.source
            - aa/virus_secondary_aa/sequenceDB
            - aa/virus_secondary_aa/sequenceDB.dbtype
            - aa/virus_secondary_aa/sequenceDB_delnodes.dmp
            - aa/virus_secondary_aa/sequenceDB_h
            - aa/virus_secondary_aa/sequenceDB_h.dbtype
            - aa/virus_secondary_aa/sequenceDB_h.index
            - aa/virus_secondary_aa/sequenceDB.index
            - aa/virus_secondary_aa/sequenceDB.lookup
            - aa/virus_secondary_aa/sequenceDB_mapping
            - aa/virus_secondary_aa/sequenceDB_merged.dmp
            - aa/virus_secondary_aa/sequenceDB_names.dmp
            - aa/virus_secondary_aa/sequenceDB_nodes.dmp
            - aa/virus_secondary_aa/sequenceDB.source
            - host/bat/masked_ref.fa.gz
            - host/camel/masked_ref.fa.gz
            - host/cat/masked_ref.fa.gz
            - host/celegans/masked_ref.fa.gz
            - host/cow/masked_ref.fa.gz
            - host/dog/masked_ref.fa.gz
            - host/human/masked_ref.fa.gz
            - host/macaque/masked_ref.fa.gz
            - host/mosquito/masked_ref.fa.gz
            - host/mouse/masked_ref.fa.gz
            - host/rat/masked_ref.fa.gz
            - host/tick/masked_ref.fa.gz
            - host/virus_shred.fasta.gz
            - nt/virus_primary_nt/sequenceDB
            - nt/virus_primary_nt/sequenceDB.dbtype
            - nt/virus_primary_nt/sequenceDB_h
            - nt/virus_primary_nt/sequenceDB_h.dbtype
            - nt/virus_primary_nt/sequenceDB_h.index
            - nt/virus_primary_nt/sequenceDB.index
            - nt/virus_primary_nt/sequenceDB.lookup
            - nt/virus_primary_nt/sequenceDB.source
            - nt/virus_secondary_nt/sequenceDB
            - nt/virus_secondary_nt/sequenceDB.dbtype
            - nt/virus_secondary_nt/sequenceDB_h
            - nt/virus_secondary_nt/sequenceDB_h.dbtype
            - nt/virus_secondary_nt/sequenceDB_h.index
            - nt/virus_secondary_nt/sequenceDB.index
            - nt/virus_secondary_nt/sequenceDB.lookup
            - nt/virus_secondary_nt/sequenceDB.source
            - tables/2020_07_27_Viral_classification_table_ICTV2019.txt
            - tables/phage_taxonomic_lineages_12102020.txt
    dbtax:
        url:
            "https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz"
        md5:
            "https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz.md5"
        tar:
            "taxdump.tar.gz"
        files:
            - tax/taxonomy/citations.dmp
            - tax/taxonomy/delnodes.dmp
            - tax/taxonomy/division.dmp
            - tax/taxonomy/gc.prt
            - tax/taxonomy/gencode.dmp
            - tax/taxonomy/merged.dmp
            - tax/taxonomy/names.dmp
            - tax/taxonomy/nodes.dmp
    dbvirRefSeq:
        url:
            "https://ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.1.1.genomic.fna.gz"
        file:
            viral.1.1.genomic.fna.gz